In [6]:
# creating arrays :
import array
arr = array.array('i',[2,4,6,8,14])
print ("new creat array:",end="")
for i in range (0,5):
 print(arr[i],end="")
print("\r")

new creat array:246814


In [11]:
import pandas as pd
dict = {'name':["ram","shyam","shytam","shubham"],"age":["23","45","56","78"]}
df = pd.DataFrame(dict,index=[True,True,False,True])
print(df)

print("\n accessing the name and age  only true value :")
print(df.loc[True])

          name age
True       ram  23
True     shyam  45
False   shytam  56
True   shubham  78

 accessing the name and age  only true value :
         name age
True      ram  23
True    shyam  45
True  shubham  78


In [17]:
#Reshaping array
import numpy as np
arr = np.arange(24)
print("the orignal array :\n",arr)
# shape array with 2 rows and 8 columns :
arr = np.arange(24).reshape(3,8)
print("\n reshapedarray:\n",arr)
arr=np.arange(24).reshape(8,3)
print("\nreshaped array:\n",arr)









the orignal array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

 reshapedarray:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

reshaped array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
